-- MySQL Script generated by MySQL Workbench
-- Wed Sep 21 13:50:12 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema xpacs
-- -----------------------------------------------------
-- Xtra PACS database
DROP SCHEMA IF EXISTS `xpacs` ;

-- -----------------------------------------------------
-- Schema xpacs
--
-- Xtra PACS database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xpacs` DEFAULT CHARACTER SET utf8 ;
USE `xpacs` ;

-- -----------------------------------------------------
-- Table `xpacs`.`PATIENT_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpacs`.`PATIENT_HISTORY` (
  `id` INT NOT NULL,
  `PACS_patient_id` VARCHAR(16) NOT NULL,
  `PACS_study_iuid` VARCHAR(45) NULL,
  `event_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xpacs`.`CAP_MODEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpacs`.`CAP_MODEL` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Type` VARCHAR(255) NULL,
  `Format` VARCHAR(255) NULL,
  `Comment` VARCHAR(2500) NULL,
  `ModelData` LONGBLOB NULL COMMENT 'Model definition stored as a zip file (BLOB)',
  `XMLData` LONGBLOB NULL COMMENT 'Contains XML metadata information.',
  `PATIENT_HISTORY_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CAP_MODEL_PATIENT_HISTORY1_idx` (`PATIENT_HISTORY_id` ASC),
  CONSTRAINT `fk_CAP_MODEL_PATIENT_HISTORY1`
    FOREIGN KEY (`PATIENT_HISTORY_id`)
    REFERENCES `xpacs`.`PATIENT_HISTORY` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xpacs`.`AUX_FILE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpacs`.`AUX_FILE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `URI` VARCHAR(255) NULL,
  `Filename` VARCHAR(255) NULL,
  `Descriptor` VARCHAR(255) NULL,
  `PATIENT_HISTORY_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_AUX_FILE_PATIENT_HISTORY1_idx` (`PATIENT_HISTORY_id` ASC),
  CONSTRAINT `fk_AUX_FILE_PATIENT_HISTORY1`
    FOREIGN KEY (`PATIENT_HISTORY_id`)
    REFERENCES `xpacs`.`PATIENT_HISTORY` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xpacs`.`CLINICAL_NOTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpacs`.`CLINICAL_NOTE` (
  `id` INT NOT NULL,
  `Age` VARCHAR(64) NULL,
  `Weight` VARCHAR(64) NULL,
  `Height` VARCHAR(64) NULL,
  `Diagnosis` VARCHAR(255) NULL,
  `Procedure` VARCHAR(255) NULL,
  `Notes` VARCHAR(2500) NULL,
  `PATIENT_HISTORY_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CLINICAL_NOTE_PATIENT_HISTORY1_idx` (`PATIENT_HISTORY_id` ASC),
  CONSTRAINT `fk_CLINICAL_NOTE_PATIENT_HISTORY1`
    FOREIGN KEY (`PATIENT_HISTORY_id`)
    REFERENCES `xpacs`.`PATIENT_HISTORY` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xpacs`.`BASELINE_DIAGNOSIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpacs`.`BASELINE_DIAGNOSIS` (
  `id` BIGINT(20) NOT NULL,
  `Height` VARCHAR(64) NULL,
  `Weight` VARCHAR(64) NULL,
  `SBP` VARCHAR(64) NULL,
  `DBP` VARCHAR(64) NULL,
  `HeartRate` VARCHAR(64) NULL,
  `HistoryOfHypertension` VARCHAR(16) NULL,
  `HistoryOfDiabetes` VARCHAR(16) NULL,
  `HistoryOfAlcohol` VARCHAR(16) NULL,
  `HistoryOfSmoking` VARCHAR(16) NULL,
  `PATIENT_HISTORY_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_BASELINE_DIAGNOSIS_PATIENT_HISTORY1_idx` (`PATIENT_HISTORY_id` ASC),
  CONSTRAINT `fk_BASELINE_DIAGNOSIS_PATIENT_HISTORY1`
    FOREIGN KEY (`PATIENT_HISTORY_id`)
    REFERENCES `xpacs`.`PATIENT_HISTORY` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `xpacs`.`PATIENT_INFO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xpacs`.`PATIENT_INFO` (
  `id` INT NOT NULL,
  `PACS_patient_id` VARCHAR(16) NOT NULL,
  `Age` VARCHAR(45) NULL,
  `Gender` VARCHAR(45) NULL,
  `Ethnicity` VARCHAR(45) NULL,
  `Cohort` VARCHAR(45) NULL,
  `PrimaryDiagnosis` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
